name:    test-server
version: "0.0.0"

dependencies:
- base
- yesod-core >= 1.6
- containers
- yesod-form
- conduit
- resourcet
- bytestring
- filepath
- text
- friday
- friday-juicypixels
- JuicyPixels
- word8
- cereal
# The library contains all of our application code. The executable
# defined below is just a thin wrapper.
library:
  source-dirs: src

# Runnable executable for our application
executables:
  test-server:
    main: Main.hs
    source-dirs: app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - test-server
